# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy Node.js app to Azure Web App - app-002-gen10-step3-1-node-oshima28

on:
  push:
    branches: [ main ]
  workflow_dispatch:

concurrency:
  group: app-002-gen10-step3-1-node-oshima28
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install deps and build
        env:
          NEXT_PUBLIC_API_ENDPOINT: ${{ secrets.NEXT_PUBLIC_API_ENDPOINT }}
          NEXT_TELEMETRY_DISABLED: 1
        run: |
          npm ci
          npm run build

      - name: Prepare deploy folder (Next.js standalone)
        run: |
          mkdir -p deploy/.next
          cp -r .next/standalone/* deploy/
          cp -r .next/static deploy/.next/
          if [ -d public ]; then cp -r public deploy/public; fi

      - name: Zip artifact
        run: zip -r app.zip deploy

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: app
          path: app.zip

  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: app

      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v3
        with:
          app-name: app-002-gen10-step3-1-node-oshima28
          slot-name: Production
          package: app.zip
          publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE_04C0BC1971B54E1C8E75C658F52FEEF5 }}
